version: '2'

volumes:
  nodered-data:
  mosquitto-data:
  mosquitto-log:

services:
  nodered:
    build: ./node-red
    ports:
      - "80:1880"
    volumes:
      - "nodered-data:/data"
    depends_on:
      - mosquitto

  mosquitto:
    build: ./mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "mosquitto-data:/mosquitto/data"
      - "mosquitto-log:/mosquitto/log"

  avahi:
    build: ./avahi
    container_name: avahi
    privileged: true
    labels:
      io.resin.features.dbus: '1'

  firewall:
    build: ./firewall
    container_name: firewall
    privileged: true
    labels:
      io.resin.features.dbus: '1'
